### ISSUE TITLE
[Query] Key size

### ISSUE THREAD

**Issue by vzool** [paragonie/sapient#14]
Hi,
I like the idea of this library and I'm doing an implementation for `golang`. But, I did start building with the key size **32 bytes** then when I try to check `Chronicle` while using it I noticed the `Secret Key` is **64 bytes** and `Public Key` is **32 bytes**. Is docs [here](https://github.com/paragonie/sapient/blame/master/docs/Internals/CryptographyKey.md#L6) correct or there is a typo?
Or **32 bytes** is the minimum key size for Secret and Public keys?

Thanks

**Comment by paragonie-scott** [comment]
It's using libsodium.

* `SigningSecretKey` is 64 bytes
* `SigningPublicKey` is 32 bytes
* `SealingSecretKey` is 32 bytes
* `SealingPublicKey` is 32 bytes

This is because

* `SigningSecretKey` corresponds to a secret key for `crypto_sign_detached()`
* `SigningPublicKey` corresponds to a public key for `crypto_sign_verify_detached()`
* `SealingSecretKey` corresponds to a secret key for `crypto_box_seal_open()`
* `SealingPublicKey` corresponds to a public key for `crypto_box_seal()`

The document you linked to discusses asymmetric public keys and (derived) symmetric shared secrets. Your public keys and the Xsalsa20poly1305 key used internally by `crypto_box_seal()` are both 32 bytes.

**Comment by vzool** [comment]
Aha cool, so the `SharedKey` in the **Chronicle** is the `PublicID` which stored in database, right?

**Comment by vzool** [comment]
> The document you linked to discusses asymmetric public keys and (derived) symmetric shared secrets. Your public keys and the Xsalsa20poly1305 key used internally by `crypto_box_seal()` are both 32 bytes.

Oh sorry, I missed that. I'm still in "**SharedKey**" phase. ^_^

BTW, I can encode/decode base64url correctly but **without double equal signs at the end**. Why that?

```php
// PHP
(hif8ITPZzhOmZmj_qKn3njVWimUWxQaDpHarkXGHeptO1z96SRk_af_n5r7D72zpkHMMr53wrapPjpBI1HS65w==) 
// Golang
(hif8ITPZzhOmZmj_qKn3njVWimUWxQaDpHarkXGHeptO1z96SRk_af_n5r7D72zpkHMMr53wrapPjpBI1HS65w)
```

Thanks

**Comment by vzool** [comment]
Which Encoded keys could have "**=**" padding or "**==**" padding?  Thanks

**Comment by vzool** [comment]
After set some focus I could figured it out, ha ha ha. Thanks buddy <3
