### ISSUE TITLE
Introduce a generic adapter

### ISSUE THREAD

**Issue by paragonie-scott** [paragonie/sapient#7]
See the discussion in #6, for when no suitable adapter is provided (i.e. no Guzzle). We just need to provide implementations for the following classes:

* `RequestInterface`
* `ResponseInterface`
* `StreamInterface`

**Comment by djsmithme** [comment]
+1. This looks like something I need. I was thinking of doing something with the adaptor when I get them time, passing a ResponseInterface to the construct and then using that instead of 'new Response' in the methods should make it compatible with any PSR7 library- this could in turn be used with the PSR7/Symfony bridge.

**Comment by paragonie-scott** [comment]
As it stands since v0.3.0, [we only use the PSR-7 interfaces](https://github.com/paragonie/sapient/blob/ef7337c1383defdc0176b7eaf55abc604d18f41d/src/Sapient.php#L19-L23) in the `Sapient` class. :)

**Comment by paragonie-scott** [comment]
Done in https://github.com/paragonie/sapient/commit/f3a69a0f2272065b6c5d5bb43ab0a4a2d9c62486
