### ISSUE TITLE
Adapters for Various Community Projects

### ISSUE THREAD

**Issue by paragonie-scott** [paragonie/sapient#8]
- [x] [Guzzle](http://docs.guzzlephp.org/en/stable/) (Adapter included)
- [x] [Slim Framework](https://www.slimframework.com/) ([Adapter](https://github.com/paragonie/slim-sapient))
- [x] [Diactoros](https://github.com/zendframework/zend-diactoros) (Zend)
- [ ] [Symfony](http://symfony.com/)
   * Laravel should automatically support this, but double-check that assumption

Feel free to suggest more, and/or develop your own.

**What to do if your framework doesn't support PSR-7**:

First, create your own PSR-7 implementation (or reuse e.g. Slim's). Then create methods that convert between the PSR-7 objects and your framework's non-compliant Request/Response objects.

**Comment by mcordingley** [comment]
I'm working on a package for Laravel.

**Comment by paragonie-scott** [comment]
Great! Will that cover Symfony users too? Or do I still need to make one.

**Comment by mcordingley** [comment]
It will not. 👎 I'm going for a high level of integration with the framework.

The bonus is that building this will give me good feedback to give you in terms of what your code needs to do to be used well externally.

**Comment by theofidry** [comment]
It would be shame to add a supprt for Illuminate but not HttpFoundation. Also if all the adapters are going to live in this repository, I recommend you get to take a look at bamarni/composer-bin-plugin and theofidry/composer-inheritance-plugin which will be of a great help. You can check nelmio/alice or theofidryAliceDataFixtures for real examples

**Comment by paragonie-scott** [comment]
>  Also if all the adapters are going to live in this repository

They aren't. See: https://github.com/paragonie/slim-sapient

**Comment by mcordingley** [comment]
@theofidry I think the way that this is going, @paragonie-scott is going to write an adapter for HttpFoundation and the Laravel integration would most likely end up using that, since it appears that all Laravel Requests and Responses inherit from HttpFoundation and that there are cases within Laravel that it makes sense to return one of the Symfony objects. (`StreamedResponse`, for instance.)

**Comment by paragonie-scott** [comment]
Today got busy, but I'll shoot for the HttpFoundation adapter before tomorrow.

**Comment by paragonie-scott** [comment]
Suggested: https://twitter.com/localheinz/status/878362860342194177

**Comment by mcordingley** [comment]
Repo for the Laravel integration: https://github.com/mcordingley/LaravelSapient The middleware are still very much pending the Symfony adapter, as are any meaningful tests.

**Comment by paragonie-scott** [comment]
Symfony is wierd. Their "PSR-7 Bridge" for their HttpFoundation says to use Diactoros, for which I just finished [an implementation](https://github.com/paragonie/zend-diactoros-sapient).

https://github.com/symfony/psr-http-message-bridge/blob/147a2381f2b887ccc57c82887a6ab7efeacf42d3/composer.json#L26-L29

If anyone wants to tackle Symfony/Laravel, I'll be happy to add it to the README later.

**Comment by mcordingley** [comment]
Looks like for Symfony, Diactoros _is_ the implementation of PSR-7 used. Since the Symfony objects don't implement PSR-7, you have to convert from PSR-7 to HttpFoundation. As such, it's not possible to build an adapter for Symfony, per se. The solution instead is to use the Diastoros adapter and then convert the request and response objects using the PSR-7 bridge on their way into or out of the Sapient instance.

**Comment by paragonie-scott** [comment]
That seems hacky, but if that's normal for Symfony, I guess that's fine. Is that true of Laravel too?

**Comment by mcordingley** [comment]
It's actually slightly worse. 😄 You do what do you do for Symfony with the responses. For requests, you do the same thing, _and then_ convert the Symfony request into a Laravel request.

**Comment by mcordingley** [comment]
https://github.com/mcordingley/LaravelSapient is ready for (tentative) use. This does NOT provide Symfony support, though it may provide useful reference material for someone wishing to implement a Symfony adapter. I'll mark it 1.0 once Sapient is 1.0 and I've had a chance to dog-food it.

**Comment by theofidry** [comment]
@paragonie-scott I think it was done that way because at the time when the PSR-7 bridge was written, Diactoros was the de-facto standard. Maybe it could be refactored a little to allow it. That said most Symfony user don't notice the difference as using PSR-7 is just a matter of changing the typehint in the Controller methods, Symfony does the rest.
